#replacing some stuff
cp updater-script ./META-INF/com/google/android/updater-script
cp -rf ./lib ./system
mkdir ./system/sd
touch ./system/sd/placeholder
#linked binaries
rm ./system/bin/cat
rm ./system/bin/cmp
rm ./system/bin/date
rm ./system/bin/dd
rm ./system/bin/dmesg
rm ./system/bin/getevent
rm ./system/bin/getprop
rm ./system/bin/hd
rm ./system/bin/id
rm ./system/bin/ifconfig
rm ./system/bin/iftop
rm ./system/bin/insmod
rm ./system/bin/ioctl
rm ./system/bin/ionice
rm ./system/bin/kill
rm ./system/bin/log
rm ./system/bin/lsmod
rm ./system/bin/nandread
rm ./system/bin/netstat
rm ./system/bin/newfs_msdos
rm ./system/bin/notify
rm ./system/bin/printenv
rm ./system/bin/ps
rm ./system/bin/reboot
rm ./system/bin/renice
rm ./system/bin/rmdir
rm ./system/bin/rmmod
rm ./system/bin/route
rm ./system/bin/schedtop
rm ./system/bin/sendevent
rm ./system/bin/setconsole
rm ./system/bin/setprop
rm ./system/bin/sleep
rm ./system/bin/smd
rm ./system/bin/start
rm ./system/bin/stop
rm ./system/bin/sync
rm ./system/bin/top
rm ./system/bin/uptime
rm ./system/bin/vmstat
rm ./system/bin/watchprops
rm ./system/bin/wipe
#linked xbinaries
rm ./system/xbin/[
rm ./system/xbin/[[
rm ./system/xbin/arp
rm ./system/xbin/ash
rm ./system/xbin/awk
rm ./system/xbin/base64
rm ./system/xbin/basename
rm ./system/xbin/bbconfig
rm ./system/xbin/blockdev
rm ./system/xbin/brctl
rm ./system/xbin/bunzip2
rm ./system/xbin/bzcat
rm ./system/xbin/bzip2
rm ./system/xbin/cal
rm ./system/xbin/cat
rm ./system/xbin/catv
rm ./system/xbin/chattr
rm ./system/xbin/chgrp
rm ./system/xbin/chmod
rm ./system/xbin/chown
rm ./system/xbin/chroot
rm ./system/xbin/clear
rm ./system/xbin/cmp
rm ./system/xbin/comm
rm ./system/xbin/cp
rm ./system/xbin/cpio
rm ./system/xbin/crond
rm ./system/xbin/crontab
rm ./system/xbin/cut
rm ./system/xbin/date
rm ./system/xbin/dc
rm ./system/xbin/dd
rm ./system/xbin/depmod
rm ./system/xbin/devmem
rm ./system/xbin/df
rm ./system/xbin/diff
rm ./system/xbin/dirname
rm ./system/xbin/dmesg
rm ./system/xbin/dnsd
rm ./system/xbin/dos2unix
rm ./system/xbin/du
rm ./system/xbin/echo
rm ./system/xbin/ed
rm ./system/xbin/egrep
rm ./system/xbin/env
rm ./system/xbin/expand
rm ./system/xbin/expr
rm ./system/xbin/false
rm ./system/xbin/fdisk
rm ./system/xbin/fgrep
rm ./system/xbin/find
rm ./system/xbin/flashcp
rm ./system/xbin/flash_lock
rm ./system/xbin/flash_unlock
rm ./system/xbin/flock
rm ./system/xbin/fold
rm ./system/xbin/free
rm ./system/xbin/freeramdisk
rm ./system/xbin/fsync
rm ./system/xbin/ftpget
rm ./system/xbin/ftpput
rm ./system/xbin/fuser
rm ./system/xbin/getopt
rm ./system/xbin/grep
rm ./system/xbin/groups
rm ./system/xbin/gunzip
rm ./system/xbin/gzip
rm ./system/xbin/halt
rm ./system/xbin/head
rm ./system/xbin/hexdump
rm ./system/xbin/id
rm ./system/xbin/ifconfig
rm ./system/xbin/insmod
rm ./system/xbin/install
rm ./system/xbin/iostat
rm ./system/xbin/ip
rm ./system/xbin/iwconfig
rm ./system/xbin/iwgetid
rm ./system/xbin/iwlist
rm ./system/xbin/iwpriv
rm ./system/xbin/iwspy
rm ./system/xbin/kill
rm ./system/xbin/killall
rm ./system/xbin/killall5
rm ./system/xbin/length
rm ./system/xbin/less
rm ./system/xbin/ln
rm ./system/xbin/losetup
rm ./system/xbin/ls
rm ./system/xbin/lsattr
rm ./system/xbin/lsmod
rm ./system/xbin/lsusb
rm ./system/xbin/lzcat
rm ./system/xbin/lzma
rm ./system/xbin/lzop
rm ./system/xbin/lzopcat
rm ./system/xbin/man
rm ./system/xbin/md5sum
rm ./system/xbin/mesg
rm ./system/xbin/mkdir
rm ./system/xbin/mke2fs
rm ./system/xbin/mkfifo
rm ./system/xbin/mkfs.ext2
rm ./system/xbin/mkfs.vfat
rm ./system/xbin/mknod
rm ./system/xbin/mkswap
rm ./system/xbin/mktemp
rm ./system/xbin/modinfo
rm ./system/xbin/modprobe
rm ./system/xbin/more
rm ./system/xbin/mount
rm ./system/xbin/mountpoint
rm ./system/xbin/mpstat
rm ./system/xbin/mv
rm ./system/xbin/nanddump
rm ./system/xbin/nandwrite
rm ./system/xbin/netstat
rm ./system/xbin/nice
rm ./system/xbin/nohup
rm ./system/xbin/nslookup
rm ./system/xbin/ntpd
rm ./system/xbin/od
rm ./system/xbin/patch
rm ./system/xbin/pgrep
rm ./system/xbin/pidof
rm ./system/xbin/ping
rm ./system/xbin/pkill
rm ./system/xbin/pmap
rm ./system/xbin/poweroff
rm ./system/xbin/printenv
rm ./system/xbin/printf
rm ./system/xbin/ps
rm ./system/xbin/pstree
rm ./system/xbin/pwd
rm ./system/xbin/pwdx
rm ./system/xbin/rdev
rm ./system/xbin/readlink
rm ./system/xbin/realpath
rm ./system/xbin/renice
rm ./system/xbin/reset
rm ./system/xbin/resize
rm ./system/xbin/rev
rm ./system/xbin/rm
rm ./system/xbin/rmdir
rm ./system/xbin/rmmod
rm ./system/xbin/route
rm ./system/xbin/run-parts
rm ./system/xbin/rx
rm ./system/xbin/sed
rm ./system/xbin/seq
rm ./system/xbin/setconsole
rm ./system/xbin/setserial
rm ./system/xbin/setsid
rm ./system/xbin/sh
rm ./system/xbin/sha1sum
rm ./system/xbin/sha256sum
rm ./system/xbin/sha512sum
rm ./system/xbin/sleep
rm ./system/xbin/sort
rm ./system/xbin/split
rm ./system/xbin/stat
rm ./system/xbin/strings
rm ./system/xbin/stty
rm ./system/xbin/sum
rm ./system/xbin/swapoff
rm ./system/xbin/swapon
rm ./system/xbin/sync
rm ./system/xbin/sysctl
rm ./system/xbin/tac
rm ./system/xbin/tail
rm ./system/xbin/tar
rm ./system/xbin/tee
rm ./system/xbin/telnet
rm ./system/xbin/telnetd
rm ./system/xbin/test
rm ./system/xbin/tftp
rm ./system/xbin/tftpd
rm ./system/xbin/time
rm ./system/xbin/timeout
rm ./system/xbin/top
rm ./system/xbin/touch
rm ./system/xbin/tr
rm ./system/xbin/traceroute
rm ./system/xbin/true
rm ./system/xbin/tty
rm ./system/xbin/ttysize
rm ./system/xbin/tune2fs
rm ./system/xbin/umount
rm ./system/xbin/uname
rm ./system/xbin/uncompress
rm ./system/xbin/unexpand
rm ./system/xbin/uniq
rm ./system/xbin/unix2dos
rm ./system/xbin/unlzma
rm ./system/xbin/unlzop
rm ./system/xbin/unxz
rm ./system/xbin/unzip
rm ./system/xbin/uptime
rm ./system/xbin/usleep
rm ./system/xbin/uudecode
rm ./system/xbin/uuencode
rm ./system/xbin/vi
rm ./system/xbin/watch
rm ./system/xbin/wc
rm ./system/xbin/wget
rm ./system/xbin/which
rm ./system/xbin/whoami
rm ./system/xbin/xargs
rm ./system/xbin/xz
rm ./system/xbin/xzcat
rm ./system/xbin/yes
rm ./system/xbin/zcat

